name = "ouyu-rental"
pages_build_output_dir = "."
compatibility_date = "2025-06-01"

[[d1_databases]]
binding = "DB"
database_name = "ouyu-db"
database_id = "10c30d31-1375-4999-ac9d-3a1a8e977f88"

[env.production]
name = "ouyu-rental"

[[env.production.d1_databases]]
binding = "DB"
database_name = "ouyu-db"
database_id = "10c30d31-1375-4999-ac9d-3a1a8e977f88"
